On branch master  Your branch is up to date with 'origin/master'.
 Changes to be committed:
	modified:   Dockerfile
	modified:   install.sh
	modified:   src/ext/sockjs/tornado/router.py

Error following

root@cd0dbd10ad2b:/astrobox# python run
Traceback (most recent call last):
  File "run", line 11, in <module>
    import octoprint
  File "/astrobox/octoprint/__init__.py", line 5, in <module>
    from octoprint.server import Server
  File "/astrobox/octoprint/server/__init__.py", line 15, in <module>
    from ext.sockjs.tornado import SockJSRouter
  File "/astrobox/ext/sockjs/tornado/__init__.py", line 3, in <module>
    from .router import SockJSRouter
  File "/astrobox/ext/sockjs/tornado/router.py", line 11, in <module>
    from sockjs.tornado import transports, session, sessioncontainer, static, stats, proto
ImportError: No module named sockjs.tornado

I found that the folder ext/sockjs/tornado exists

Trying to change router.py